version: '3.7'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    platform: linux/amd64
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Abc12345
      - MSSQL_PID=Developer
      - MSSQL_TCP_PORT=1433
    ports:
      - 1433:1433
